repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.4.2
  hooks:
    - id: black
      language_version: python3.10

- repo: local
  hooks:
    - id: readme-generation
      name: Generates the readme
      entry: python -m script.generate_readme
      language: system
      types: [python]